author: Donrwalsh
description: "Introduction to Algorithms (CLRS) Solutions"
url: "https://donrwalsh.github.io"

collections:
  solutions:
    output: true
highlighter: rouge
baseurl: /CLRS

# Google Analytics
google_analytics_id: "UA-160627836-1"
keywords: "algorithms, CLRS, Cormen, Leiserson, Rivest, Stein, solutions"