description: "Introduction to Algorithms (CLRS) Solutions"

collections:
  solutions:
    output: true
highlighter: rouge
baseurl: /CLRS

# Google Analytics
google_analytics_id: "UA-160627836-1"
keywords: "algorithms, CLRS, Cormen, Leiserson, Rivest, Stein, solutions"